title: Use bold and italic text
hero_image: images/banner.png
description: Use bold and italic text.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Use bold and italic text
